services:
  - type: web
    name: kuet-energy-co2
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --workers 2 --threads 4 --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
